### ISSUE TITLE
swamp-eclipse-plugin not found in eclipse marketplace

### ISSUE THREAD

**Issue by jbasney** [mirswamp/swamp-eclipse-plugin#1]
Following the instructions in Section 2.2 of https://github.com/mirswamp/swamp-eclipse-plugin/blob/master/README.adoc I searched for SWAMP in the Eclipse Marketplace and got back 0 matches. I also don't find the plug-in when searching at https://marketplace.eclipse.org/search/site/SWAMP. Is it not yet available in the Eclipse Marketplace or am I doing something wrong?

I'm using Eclipse IDE for Java Developers Neon.3 Release (4.6.3) on MacOS.

![eclipse-marketplace](https://cloud.githubusercontent.com/assets/148492/24370352/b4fcea30-12ec-11e7-8715-a538e9e145f2.png)

**Comment by mdreid** [comment]
Hi Jim,

The SWAMP Eclipse plug-in is not available on the Eclipse Marketplace yet as we are still in the process of creating an update site. I will let you know when it's available via the Marketplace.

**Comment by mdreid** [comment]
SWAMP Eclipse plug-in now available on Eclipse Marketplace
