### ISSUE TITLE
Problem Occurred: Argument cannot be null

### ISSUE THREAD

**Issue by jbasney** [mirswamp/swamp-eclipse-plugin#5]
When using the SWAMP perspective to view results, I get:

    An error has occurred. See error log for more details.
    Argument cannot be null 

![swamp-error2](https://cloud.githubusercontent.com/assets/148492/24374243/c17ece6a-12f9-11e7-8651-bc74aaaeadb1.png)

Using 2017-03-14-swamp_eclipse_plugin.zip with Eclipse IDE for Java Developers Neon.3 Release (4.6.3) on MacOS.

Is there some way for me to get a stack trace or other additional information out of the plugin to help with debugging this error?

**Comment by mdreid** [comment]
Hi Jim,

Can you please add the error log here and describe your workflow? I am adding better logging in the coming weeks.

The error log can be found by clicking "Installation Details" in the "Help" menu, selecting the "Configuration" tab and clicking "View Error Log"

**Comment by jbasney** [comment]
[log.txt](https://github.com/mirswamp/swamp-eclipse-plugin/files/873942/log.txt)

The error occurs when I open the SWAMPHttpClient.java or Session.java source files but not when I open PackageVersion.java or MyResponse.java or HTTPException.java. So... what's the common factor? This screenshot may give a clue:

![null](https://cloud.githubusercontent.com/assets/148492/24380228/f27ba982-130f-11e7-96dc-fa61a9a65e50.png)

Notice how Group, Tool, and Platform are empty for the last weakness, on line 56. Oh, that's from error-prone:

    <AnalyzerReport tool_version="2.0.15" tool_name="error-prone" uuid="e6004910-7ec9-4b24-b2ff-6e5d1e829015">
    ...
    <BugInstance id="5">
      <Methods></Methods>
      <BugLocations>
        <Location id="1" primary="true">
          <SourceFile>swamp-java-api/src/main/java/org/continuousassurance/swamp/session/SWAMPHttpClient.java</SourceFile>
          <StartLine>56</StartLine>
          <EndLine>56</EndLine>
          <StartColumn>11</StartColumn>
          <EndColumn>11</EndColumn>
        </Location>
      </BugLocations>
      <BugCode>ClassCanBeStatic</BugCode>
      <BugSeverity>warning</BugSeverity>
      <BugMessage>[ClassCanBeStatic] Inner class is non-static but does not reference enclosing class</BugMessage>
      <ResolutionSuggestion>Did you mean 'public static class MySSLConfiguration extends SSLConfiguration implements Serializable {'?</ResolutionSuggestion>
      <BugTrace>
        <BuildId>1</BuildId>
        <AssessmentReportFile>assessment_report1.out</AssessmentReportFile>
        <InstanceLocation>
          <LineNum>
            <Start>20</Start>
            <End>24</End>
          </LineNum>
        </InstanceLocation>
      </BugTrace>
    </BugInstance>

Yup, sure enough, I get the Eclipse error for any source files for which error-prone reported a weakness.

**Comment by mdreid** [comment]
OK, I'm successfully reproducing this behavior

**Comment by mdreid** [comment]
Confirmed fix. I'm going to close this issue as fixed. If you run into it again, please re-open. The fix will be in tonight's release.

Source of bug: SCARF XML reader was not initializing certain instance variables (including some Strings). If these Strings were for fields that may not be in SCARF, when we try to populate the Weaknesses Table with the fields, we do row.setText(rowIndex, null) which throws an exception rather than row.setText(rowIndex, ""). 

Fix: Initialize strings to empty string in SCARF XML reader. Replace the old version with the new version as a dependency
